### ISSUE TITLE
ignoreInitialState not working

### ISSUE THREAD

**Issue by imageslr** [omnidan/redux-undo#234]
Hello, I'm using redux-undo following the `README.md`. I have set `ignoreInitialState = true`, but I still can undo to the beginning `@@INIT`.

## Describe
When app is mounted, it will fetch data from server and dispatch `INIT_STATE` action to init the state. There will be two commits:
![image](https://user-images.githubusercontent.com/17822028/61780156-956d2000-ae34-11e9-8be1-fce2be73210d.png)

I have  set `ignoreInitialState` as `true`, but from right panel above I can see that `past` array contains the initial state. Thus if I press `ctrl + z`, which will dispatch `ActionCreators.undo()`, state will return to the initial state. But I hope I can only undo to the second commit --- `INIT_STATE`. 

## Code
My code is very simple. 

Here is my `reducer.ts`:
```ts
function reducer(state = INITIAL_STATE, action): SettingState {
  switch (action.type) {
    case ActionTypes.INIT_STATE:
      return action.payload.state;
    case ActionTypes.SET_STATE:
      return action.payload.state;
    default:
      return state;
  }
}

export default undoable(reducer, {
  debug: true,
  ignoreInitialState: true
});
```

And here is the log of the two commits:
![image](https://user-images.githubusercontent.com/17822028/61780576-630ff280-ae35-11e9-8c61-99c009cba91b.png)

---

When I press `ctrl + z` to perform undo, state will be reset to initial state. Here is log:
![image](https://user-images.githubusercontent.com/17822028/61780667-8044c100-ae35-11e9-9b2c-5239934c57ee.png)

and state change:
![image](https://user-images.githubusercontent.com/17822028/61780694-8dfa4680-ae35-11e9-9947-8a34c2fbc969.png)

Thanks for your response!

**Comment by imageslr** [comment]
## Update
As a workaround,  I use `filter` to exclude `INIT_STATE` action:
```ts
export default undoable(reducer, {
  debug: true,
  filter: excludeAction(ActionTypes.INIT_STATE)
});
```

**Comment by imageslr** [comment]
# Update
As a workaround, I use `groupBy` to merge `@@INIT` and `INIT_STATE`. 

```ts
export default undoable(reducer, {
  debug: true,
  ignoreInitialState: true,
  groupBy: function(action: any) {
      if (action.type == "@@INIT" || action.type == ActionTypes.INIT_STATE) {
        return ActionTypes.INIT_STATE;
      }
      return null;
  }
});
```

**Comment by nmay231** [comment]
Fixed in #248 :+1:

**Comment by lbragile** [comment]
@nmay231 I believe this is still an issue unfortunately.

The simplest work around for me was to `dispatch(ActionCreators.clearHistory());` right after my app launches and sets the initial state.

This means that the configuration only needs to have:

```diff
export const rootReducer = combineReducers({
  someReducer: undoable(someReducer, {
    ...
-    ignoreInitialState: true, // not needed (doesn't work)
    syncFilter: true
  })
});
```

As a result, the history will begin being recorded only after this initial state.

Note that for the `ignoreInitialState` property to be meaningful, as I understand, an `initType` needs to be dispatched.

>   initTypes: ['@@redux-undo/INIT'], // history will be (re)set upon init action type
  // beware: those actions will not be passed down to the wrapped reducers

Which is the same as clearing the history right?

I just wasn't sure how to dispatch this type if my reducers do not have a handler for it. Also, I didn't want to add a handler for a type that I am not planning to really use in my app.

Please let me know if my reasoning/solution above makes sense (is correct/valid).

Thank you for your hard work!
